baseURL: '/'
languageCode: en-us
title: Cloud Native Rejekts
theme: rejekts

menu:
  main:
    - identifer: schedule
      name: Schedule
      url: "#schedule"
      weight: -110
    # - identifer: speakers
    #   name: Speakers
    #   url: "#speakers"
    #   weight: -110
  #  - identifer: program_committee
  #    name: Program Committee
  #    url: "#program_committee"
  #    weight: -100
  #  - identifer: venue
  #    name: Venue
  #    url: "#venue"
  #    weight: -100
    - identifer: tickets
      name: Tickets
      url: "#tickets"
      weight: -95
    - identifer: conduct
      name: Code of Conduct
      url: "#conduct"
      weight: -90
    - identifer: participation
      name: CFP
      url: "#participation"
      weight: -85
    - identifer: sponsorship
      name: Sponsors
      url: "#sponsor"
      weight: -80

permalinks:
  announcements: /announcements/:year/:month/:title/
  events: /events/:filename/

disableKinds:
- taxonomy
- term

buildFuture: false

params:
  event:
    state: cfppublished # allowed states future, next, archived
    city: Atlanta
    code: NA2025
    description: |
      Cloud Native Rejekts is the b-side conference giving a second chance to the many
      wonderful, but rejected talks leading to KubeCon + CloudNativeCon.

      Cloud Native Rejekts will be an in-person conference. We hope to see you in Atlanta, on November 8 on the heels of KubeCon NA 2025.

      See you in November!
    prospectus: Rejekts_Sponsorship_Prospectus_Europe_2025.pdf
    sponsor:
      pitch: |
        Sponsoring Cloud Native Rejekts not only supports the wider cloud native
        community leading into the week's main event. It's also a chance to present your company, product, and messaging
        in a more relaxed and fun setting than the typical trade show. Want to support the Cloud Native Rejekts Europe 2025?
      hide: true
    admission_free: true
    tickets_url: https://pretix.eu/rejekts/rejektsna25/

    schedule:
      link: https://cfp.cloud-native.rejekts.io/cloud-native-rejekts-atlanta-na-atlanta-2025/schedule/
      datetime: 2025-11-08 09:30:00
      days:
        - slots:
          - title: Talks
            time: 9:30 AM - 6:30 PM

    venue:
      name: Academy of Medicine, Georgia Institute of Technology
      address: Atlanta, GA 30332
      city: Atlanta, Georgia, USA
      website: https://studentcenter.gatech.edu/academy-medicine/space/entire-building
      maplink: https://maps.app.goo.gl/GFDABAM77irxvrRh7
      embedded_map: |
        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d829.0786384199534!2d-84.3877921!3d33.7783744!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88f50467cecb6c7f%3A0x711487abe50b65de!2sThe%20Historic%20Academy%20of%20Medicine!5e0!3m2!1sen!2sde!4v1761851050438!5m2!1sen!2sde" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
      hide: false

    sponsors:
      - type: Champion
        sponsors:
        - name: Microsoft
          link: https://microsoft.com/
          logo: microsoft-azure.jpg
      - type: Supporter
        sponsors:
        - name: CNCF
          link: https://www.cncf.io/
          logo: cncf.png
        - name: Isovalent
          link: https://isovalent.com/
          logo: isovalent.png
      - type: Community
        sponsors:
        - name: Kubesimplify
          link: https://kubesimplify.com/
          logo: Kube_simplify.png
      - type: Media
        sponsors:
        - name: The New Stack
          link: https://thenewstack.io/
          logo: the-new-stack.png


    tickets:
      - type: academic
        price:
          early:
          standard:
          late:
      - type: professional
        price:
          early:
          standard:
          late:
      - type: corporate
        price:
          early:
          standard:
          late:
      - type: diversity
        price:
          early: $0
          standard: $0
          late: $0

  social:
    - title: Twitter
      url: 'https://twitter.com/rejektsio'
      image: 'twitter-icon'
    - title: Bluesky
      url: 'https://bsky.app/profile/rejekts.io'
      image: 'bluesky-icon'
    - title: Mastodon
      url: 'https://hachyderm.io/@Rejekts'
      image: 'mastodon-icon'
    - title: Instagram
      url: 'https://www.instagram.com/Rejektsio/'
      image: 'instagram-icon'
    - title: email
      url: "mailto:info@rejekts.io"
      image: 'email-icon'

  hero:
    title: Recycle your KubeCon talk here!
    hashtag: rejekts2025
    image: hero-img.svg
    description:  Cloud Native Rejekts offers attendees a weekend of ‘unaccepted’ talks leading into
                  KubeCon. It provides a stage for some of the 89% of talks rejected by KubeCon.

  participation:
    opens: Monday, July 28
    closes: Monday, August 11
    notifications: Monday, August 25
    schedule: Monday, September 1
    opens_comment: Opens after KubeCon notifications go out
    closes_comment: Two weeks after CFP opens
    description:  Cloud Native Rejekts welcomes the rejected proposals from KubeCon NA or new ones
                  that cover super fresh topics. We offer slots for 30min full-length talks and 5min
                  lightning talks. We welcome topics about...
    link: https://cfp.cloud-native.rejekts.io/cloud-native-rejekts-atlanta-na-atlanta-2025/schedule/
    status: The CFP for the Cloud Native Rejekts NA 2025 is.
    volunteer_form: https://forms.gle/R1sSnytKmMXBBmDR9
    topics: [
      "core concepts",
      "open-source components + tooling",
      "user experiences",
      "security",
      "new developments + experiments",
      "etc."
    ]

  promo:
    video:
      heading: "Video of past events"
      link: https://www.youtube.com/embed/ZJhnx2kgh80

  media:
    city: Salt Lake City, USA
    gallery:
      link: https://www.flickr.com/photos/181798830@N03/albums/72177720322076407/
      thumbnail: https://live.staticflickr.com/65535/54154966674_c59129f9f1_6k.jpg
    promo:
      video:
